---
- name: Install nginx package
  package:
    name: nginx
    state: present

- name: Start and enable nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Create nginx configuration (Debian/Ubuntu)
  template:
    src: ubuntu.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx service
