---
- name: Download WordPress
  command: "curl -o /tmp/wordpress.zip https://wordpress.org/latest.zip"
  args:
    creates: /tmp/wordpress.zip

- name: Extract WordPress
  command: "unzip -q /tmp/wordpress.zip -d /opt/"
  args:
    creates: /opt/wordpress
  register: extraction
  changed_when: extraction.rc == 0

- name: Set WordPress Permissions
  command: "chown -R www-data:www-data /opt/wordpress"
  changed_when: false

- name: Create wp-config.php
  template:
    src: wp-config.php.j2
    dest: /opt/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
  when: not (ansible_run_tags | default([]) | bool and '/opt/wordpress/wp-config.php' in ansible_run_tags)

- name: Create wordpress.conf
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-enabled/wordpress.conf
  notify: Restart Apache Service
